### ISSUE TITLE
Viewing individual spectra

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/mosviz#96] opened 2018-06-18 17:27 UTC
There is a request to be able to view individual spectra that went into the pipeline-produced combination.  (Specific to JWST currently?).  This will require some discussion with pipeline people and knowledge of the internal output formats and simulated data.

**Comment by kassin** [comment] 2018-06-18 19:03
Yes, this is specific to JWST.  Let's not go there with other telescopes/instruments since it will be too complicated.

**Comment by kassin** [comment] 2018-06-18 19:03
@mfixstsci Thoughts?

**Comment by hcferguson** [comment] 2018-06-18 19:55
The use case is not specific to JWST, but the method for saving the information on the individual spectra is going to be different for each mission. JWST uses associations.

**Comment by astrofrog** [comment] 2018-06-18 20:46
I think it'd be interesting to do a mockup of what this would look like - and if we want to visualize the different slits, we'll need to start allowing slits to have position angles.

**Comment by kassin** [comment] 2018-06-19 02:52
I don't see people using our "drill back" functionality for non-JWST data.

**Comment by kassin** [comment] 2018-06-19 02:56
There are actually 2 types of drill-backs: The first is for ramps in an individual exposure (easiest?).  The second is for combined exposures.  The latter will have to worry about multiple-PAs.  Perhaps we should have 2 separate issues?

**Comment by ibusko** [comment] 2018-07-13 14:56
If I understand this requirement correctly, the goal is to enable a more finer-grained display of the data sequence (ramps, exposures, etc) that went into the production of each cutout/sp1d/sp2d set. 

Currently mosviz displays one set at a time, based on the drop-down ID selector. My take is that this new proposed feature would provide a second drop-down (or another type of selector widget) which would allow selection of one (or perhaps more) particular ramp/exposure/whatever pertaining to the sequence corresponding to the given set. Is this correct? 

(not sure this is clear enough)

**Comment by kassin** [comment] 2018-07-13 19:55
@ibusko Correct.

**Comment by hcferguson** [comment] 2018-07-16 14:01
We have level 3 extracted spectra and level 2 extracted spectra. The difference is that the level 3 are co-adds of multiple level 2 spectra. So feature #1 is provide a simple ability to step through each of the level 2 spectra that contribute to a level 3 spectrum, examining both the 2-D and the 1-D views.

Doing anything beyond that for JWST is going to be much more difficult, and we should think carefully about whether it is even within the scope of MOSViz. Why? Because there won't be extracted 1D spectra -- and at least so far -- spectral extraction has been beyond what we thought we should provide in a quick-look viewer. 

That said, all MOSViz needs is a table of 1D and 2D spectra files, so if someone wants to view something else, they can do their own custom extraction, populate the table, and fire up MOSViz to view them without us having to code up anything new.

I would also contend that viewing portions of the ramps is out of scope for MOSViz.

**Comment by ibusko** [comment] 2018-07-16 14:37
Sounds clear enough, Harry. It's now more a matter of deciding which GUI widgets we need to enable selection of level 2 spectra. I envision a duplicate of what we have now: the Previous, Next, and drop down selectors would be duplicated with new Previous, Next, drop down controls acting on the level 2 spectra associated to whatever level 3 spectrum is currently selected. Each set of three controls should be clearly labelled in the GUI as pertaining to the level 3 and 2 data. 

There is an additional problem though: how do we provide all these spectra to MOSViz. Currently, it uses the input table to find the cutouts, 1D, and 2D files. I understand that now it will be handling an additional level of files, having similar association tables linked to each row of the input primary table. Or, are the level 2 products compacted/associated in a different way, perhaps as multiple extensions in a single FITS file? If that is the case, we will need just to add the names of these new multi-extension FITS files to the primary table.     

In any case, both level 3 and 2 will share the same, common display format created by MOSViz.

Does all this sounds right?

**Comment by ibusko** [comment] 2018-07-16 18:11
CALWEBB_SPEC2 does not perform 1D extractions. So for level 2 data we will have only 2D spectra. No cutouts or 1D spectra. So, how should MOSViz behave:

 -  keep the level 3 cutout and 1D plot on screen when displaying the level 2 2D spectrum,
or
 - hide the cutout and 1D displays when displaying level 2 2D spectrum? 

I personally favor the first one, but people may prefer otherwise.

**Comment by kassin** [comment] 2018-07-16 18:42
@ibusko Would it be difficult to prototype this in this sprint? Btw, I like bullet one above.

For work outside this sprint, I think it's really important that we have a break-out meeting on this with as many potential MOSViz users as we can.  @ibusko Would you be interested in leading this? If so, I can help you figure out who can be invited and help you schedule the meeting.

Some thoughts: 

-The ESA NIRSpec instrument team and the NIRSpec PI, for example, would like to use MOSViz for commissioning.  For commissioning, they will need to drill as far back as possible in the data.  It is unclear how far we should make it easy drill back in MOSViz (Harry's point taken about the table enabling the user to read in whatever they want, but if we want this ability, it should be more baked into the workflow).  

-Do we want MOSViz to be more than a quick-look tool with the current functionality?  If so, what additional functionality should it have?
    -I would like to be able to collapse 2D spectra to create 1D spectra with user specified limits (perhaps identified interactively with the mouse on the 2D spectrum).

**Comment by brechmos-stsci** [comment] 2018-07-17 12:54
If it is going to be anything more than a quick look type of thing then some thought should be put in as to how the display can be made as modular as possible, or better yet, extensible. For discussions Tom should be included too so we leverage Glue as much as possible.

**Comment by ibusko** [comment] 2018-07-17 13:18
@kassin I might be able to come up with a prototype if we manage to get a test data set that includes the level 2 files. 

On the issue of MOSViz as a quick look tool as opposed as a more capable data analysis tool, the fact it can be connected to SpecViz is already a large step towards that goal. Most of any additional data analysis I can envision for it would be in the 2D realm, I think. A 2D->1D collapsing capability could be put in there, for sure, but the more features we add, the heavier the tool becomes, leading to more cost to develop/maintain, and steeper learning curves for users. 

I would be happy to lead that effort, in case we actually move in that direction.

**Comment by ibusko** [comment] 2018-07-26 15:35
I committed a prototype level-2-capable version of MOSViz into my fork/branch ibusko/dev. 

The data set for helping the development was made up from the existing MOSViz test data set at /astro/3/jwst_da_sprint_testdata/mostools/workshop_examples/jwst, to which I added a level2/ subdirectory with level 2 files taken from /grp/jwst/ssb/bushouse/jwst_data/NIRSpec/MSA/MOS_UDF_G235M/. The MOSViz input table was modified to include a new column that points to the level 2 files.

The resulting test data set is located at /grp/jwst/ssb/busko/mosviz_data/jwst 

Obviously the two data sets don't match. The simulated objects in each one are different, so that results in WCS issues (that the code ignores for the moment). The formats are also different, since the two sets were created at different points in pipeline development (or so it seems to me). Thus, the data loaders must be taken as work in progress. Nevertheless, the resulting combination has been good enough to act as a initial test bed for software development and demo purposes.

**Comment by hcferguson** [comment] 2018-09-04 17:30
@ibusko You mentioned in your July 16 comment that CALWEBB_SPEC2 doesn't do 1-d extraction. I was just perusing the documentation and notice that it's checked off as doing it in the documentation (https://jwst-pipeline.readthedocs.io/en/stable/jwst/pipeline/description.html#stage2-spectroscopic-flow).  Do you know if something has changed?

**Comment by ibusko** [comment] 2018-09-04 18:19
I am not sure if something changed, or I just missed that documentation on CALWEBB_SPEC2. I am sure I got the information from somewhere though. In any case, I re-cast my question to refer just to the cutout then:

- keep the level 3 cutout on screen when displaying the level 2 2D and 1D spectra,
    or
- hide the cutout display when displaying level 2 2D and 1D spectra?

**Comment by hcferguson** [comment] 2018-09-05 19:27
@ibusko The most common use case I can think of is the following: I have a spectrum and it looks funny. Maybe the lines are broader than I think they should be. Or double-peaked. I want to go back and inspect the individual dithers and see if they look basically the same, or if the funny business is due to mis-registration. So from that perspective my preferred workflow would be to have the tool register the 1D and 2D spectra by WCS and be able to blink or cycle between them (e.g. using the tab key or some other hot key).

**Comment by ibusko** [comment] 2018-09-11 14:41
I implemented exposure (FITS extension) blinking/cycling buttons identical in behavior with the existing Next/Previous buttons.

**Closed as completed** 2018-09-20 14:23 UTC
Labels: Priority-High
