### ISSUE TITLE
_x2d WCS problem

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/mosviz#220] opened 2019-03-19 15:18 UTC
The 2D extracted spectra in the _x2d file have both spatial and spectral axes, which Astropy doesn't understand (and hence MOSViz doesn't understand). 

Reportedly this is a known issue, but I'm not sure if there is a ticket in Astropy for it.

**Comment by astrofrog** [comment] 2019-03-19 17:30
Based on the file I saw, this is not an astropy issue though, it's a bug in the production of the original _x2d file - these files shouldn't have 3D WCS coordinates in the first place, but 2D coordinates? (this is not to say the header can't contain information about the original RA/Dec pointing for instance, but it shouldn't use the WCS keywords for this).

If you want to keep track of the RA/Dec over the _x2d, you could consider providing two WCS solutions, one in offset vs spectral coordinate and one with ra vs dec, and use the ability to specify multiple WCSes by appending a suffix to the WCS keywords, e.g. ``CTYPE1A`` for the secondary coordinate system.

**Comment by astrofrog** [comment] 2019-03-19 17:44
Actually it should be possible to use WCSAXES>NAXIS but I think when I checked the x2d file the axes were in the wrong order - I’ll investigate again!

**Comment by astrofrog** [comment] 2019-03-19 18:13
Here's an example of an incorrect header:

```
...
NAXIS   =                    2 / number of array dimensions                     
NAXIS1  =                 1152                                                  
NAXIS2  =                   15              
...
WCSAXES =                    3 / number of World Coordinate System axes         
CRPIX1  =               1024.5 / axis 1 coordinate of the reference pixel       
CRPIX2  =               1024.5 / axis 2 coordinate of the reference pixel       
CRVAL1  =               5.3196 / first axis value at the reference pixel        
CRVAL2  =   -72.98605000000001 / second axis value at the reference pixel       
CTYPE1  = 'RA---TAN'           / first axis coordinate type                     
CTYPE2  = 'DEC--TAN'           / second axis coordinate type                    
CTYPE3  = 'WAVE    '           / third axis coordinate type                     
CUNIT1  = 'deg     '           / first axis units                               
CUNIT2  = 'deg     '           / second axis units                              
CUNIT3  = 'micron  '           / third axis units                               
CDELT1  = 2.86854111111111E-05 / first axis increment per pixel                 
CDELT2  = 2.92567277777777E-05 / second axis increment per pixel                
PC1_1   =                 -1.0 / linear transformation matrix element           
PC1_2   =                  0.0 / linear transformation matrix element           
PC2_1   =                  0.0 / linear transformation matrix element           
PC2_2   =                  1.0 / linear transformation matrix element
```

See also section 2.2 of http://www.atnf.csiro.au/people/mcalabre/WCS/wcs.pdf - basically the issue is that the first two CTYPES should be WAVE and then either RA or DEC, then DEC or RA, but basically WAVE has to come first because NAXIS1 corresponds to the spectral axis. It might be possible to mess with the PC matrix to specify the coordinates in a different order, but I'd recommend not doing that. I also think that CRPIX1/2 (which should be 2/3) are currently wrong - all these issues are probably due to this WCS being the one of the original 3D cube not the final 2D spectrum.

**Comment by astrofrog** [comment] 2019-03-19 18:21
The following script can be used to output the coordinates in each pixel of the data for each coordinate:

```python
import numpy as np
from astropy.io import fits
from astropy.wcs import WCS

hdu = fits.open('filename_s2d.fits')['SCI']

hdu.header['CUNIT3'] = 'um'

wcs = WCS(hdu.header)

k, j, i = np.indices((1,) + hdu.data.shape)

w1, w2, w3 = wcs.wcs_pix2world(i, j, k, 0)

fits.writeto(hdu.header['CTYPE1'][:4] + '.fits', w1, overwrite=True)
fits.writeto(hdu.header['CTYPE2'][:4] + '.fits', w2, overwrite=True)
fits.writeto(hdu.header['CTYPE3'][:4] + '.fits', w3, overwrite=True)
```

If you try this, you'll see that while RA varies along what should be the spectral axis, WAVE is constant across the array.

**Comment by astrofrog** [comment] 2019-03-21 09:47
I'm going to assign to myself as I want to investigate whether things work properly in MOSViz if the header is fixed. But in any case the WCS is definitely incorrect so this issue should be reported to whoever made the simulated data.

**Comment by jdavies-st** [comment] 2019-03-24 05:40
If this is JWST pipeline data that is `_x2d`, then the FITS WCS is not an accurate representation of any of the data (and never has been) and should not be used.  And in fact it will not be populated at all for these data in the very near future.  See

https://github.com/spacetelescope/jwst/issues/2262

The `_s2d` file produced by the JWST cal pipeline, i.e. the resampled and rectified 2D spectra should be able to be represented via normal FITS WCS, but currently astropy does not allow the use of lookup tables for dispersion (WAVE-TAB). Since many dispersers for JWST are prisms, the only way to represent the very non-linear dispersion is via lookup table.  So currently the FITS WCS in `_s2d` files are not complete.  Though the GWCS object is correct.

**Closed** 2021-07-20 18:48 UTC
Labels: Bug, won't fix
